################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/LoRaWAN/App/src/bsp.c \
C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/LoRaWAN/App/src/debug.c \
../Projects/End_Node/fft.c \
C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/LoRaWAN/App/src/hw_gpio.c \
C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/LoRaWAN/App/src/hw_rtc.c \
C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/LoRaWAN/App/src/hw_spi.c \
C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/LoRaWAN/App/src/main.c \
C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/Core/src/stm32l4xx_hal_msp.c \
C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/Core/src/stm32l4xx_hw.c \
C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/Core/src/stm32l4xx_it.c \
C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/LoRaWAN/App/src/vcom.c 

OBJS += \
./Projects/End_Node/bsp.o \
./Projects/End_Node/debug.o \
./Projects/End_Node/fft.o \
./Projects/End_Node/hw_gpio.o \
./Projects/End_Node/hw_rtc.o \
./Projects/End_Node/hw_spi.o \
./Projects/End_Node/main.o \
./Projects/End_Node/stm32l4xx_hal_msp.o \
./Projects/End_Node/stm32l4xx_hw.o \
./Projects/End_Node/stm32l4xx_it.o \
./Projects/End_Node/vcom.o 

C_DEPS += \
./Projects/End_Node/bsp.d \
./Projects/End_Node/debug.d \
./Projects/End_Node/fft.d \
./Projects/End_Node/hw_gpio.d \
./Projects/End_Node/hw_rtc.d \
./Projects/End_Node/hw_spi.d \
./Projects/End_Node/main.d \
./Projects/End_Node/stm32l4xx_hal_msp.d \
./Projects/End_Node/stm32l4xx_hw.d \
./Projects/End_Node/stm32l4xx_it.d \
./Projects/End_Node/vcom.d 


# Each subdirectory must supply rules for building sources it contributes
Projects/End_Node/bsp.o: C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/LoRaWAN/App/src/bsp.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_EU868 -DX_NUCLEO_IKS01A1 -DARM_MATH_CM4 '-D__FPU_PRESENT=1' -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/Core/inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/LoRaWAN/App/inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/STM32L4xx_Nucleo" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/STM32L4xx_HAL_Driver/Inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/Include" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Crypto" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Mac" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Phy" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Utilities" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/X_NUCLEO_IKS01A1" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/X_NUCLEO_IKS01A2" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/Common" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/hts221" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lps22hb" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lps25hb" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/sx1276" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Core" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/sx1276mb1mas" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/FFT" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lsm6ds0" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lsm6ds3" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/DSP/Source"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Projects/End_Node/debug.o: C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/LoRaWAN/App/src/debug.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_EU868 -DX_NUCLEO_IKS01A1 -DARM_MATH_CM4 '-D__FPU_PRESENT=1' -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/Core/inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/LoRaWAN/App/inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/STM32L4xx_Nucleo" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/STM32L4xx_HAL_Driver/Inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/Include" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Crypto" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Mac" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Phy" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Utilities" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/X_NUCLEO_IKS01A1" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/X_NUCLEO_IKS01A2" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/Common" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/hts221" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lps22hb" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lps25hb" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/sx1276" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Core" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/sx1276mb1mas" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/FFT" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lsm6ds0" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lsm6ds3" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/DSP/Source"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Projects/End_Node/%.o: ../Projects/End_Node/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_EU868 -DX_NUCLEO_IKS01A1 -DARM_MATH_CM4 '-D__FPU_PRESENT=1' -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/Core/inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/LoRaWAN/App/inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/STM32L4xx_Nucleo" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/STM32L4xx_HAL_Driver/Inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/Include" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Crypto" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Mac" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Phy" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Utilities" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/X_NUCLEO_IKS01A1" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/X_NUCLEO_IKS01A2" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/Common" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/hts221" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lps22hb" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lps25hb" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/sx1276" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Core" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/sx1276mb1mas" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/FFT" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lsm6ds0" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lsm6ds3" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/DSP/Source"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Projects/End_Node/hw_gpio.o: C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/LoRaWAN/App/src/hw_gpio.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_EU868 -DX_NUCLEO_IKS01A1 -DARM_MATH_CM4 '-D__FPU_PRESENT=1' -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/Core/inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/LoRaWAN/App/inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/STM32L4xx_Nucleo" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/STM32L4xx_HAL_Driver/Inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/Include" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Crypto" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Mac" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Phy" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Utilities" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/X_NUCLEO_IKS01A1" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/X_NUCLEO_IKS01A2" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/Common" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/hts221" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lps22hb" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lps25hb" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/sx1276" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Core" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/sx1276mb1mas" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/FFT" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lsm6ds0" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lsm6ds3" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/DSP/Source"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Projects/End_Node/hw_rtc.o: C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/LoRaWAN/App/src/hw_rtc.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_EU868 -DX_NUCLEO_IKS01A1 -DARM_MATH_CM4 '-D__FPU_PRESENT=1' -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/Core/inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/LoRaWAN/App/inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/STM32L4xx_Nucleo" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/STM32L4xx_HAL_Driver/Inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/Include" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Crypto" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Mac" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Phy" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Utilities" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/X_NUCLEO_IKS01A1" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/X_NUCLEO_IKS01A2" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/Common" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/hts221" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lps22hb" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lps25hb" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/sx1276" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Core" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/sx1276mb1mas" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/FFT" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lsm6ds0" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lsm6ds3" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/DSP/Source"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Projects/End_Node/hw_spi.o: C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/LoRaWAN/App/src/hw_spi.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_EU868 -DX_NUCLEO_IKS01A1 -DARM_MATH_CM4 '-D__FPU_PRESENT=1' -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/Core/inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/LoRaWAN/App/inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/STM32L4xx_Nucleo" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/STM32L4xx_HAL_Driver/Inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/Include" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Crypto" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Mac" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Phy" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Utilities" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/X_NUCLEO_IKS01A1" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/X_NUCLEO_IKS01A2" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/Common" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/hts221" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lps22hb" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lps25hb" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/sx1276" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Core" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/sx1276mb1mas" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/FFT" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lsm6ds0" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lsm6ds3" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/DSP/Source"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Projects/End_Node/main.o: C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/LoRaWAN/App/src/main.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_EU868 -DX_NUCLEO_IKS01A1 -DARM_MATH_CM4 '-D__FPU_PRESENT=1' -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/Core/inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/LoRaWAN/App/inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/STM32L4xx_Nucleo" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/STM32L4xx_HAL_Driver/Inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/Include" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Crypto" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Mac" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Phy" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Utilities" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/X_NUCLEO_IKS01A1" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/X_NUCLEO_IKS01A2" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/Common" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/hts221" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lps22hb" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lps25hb" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/sx1276" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Core" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/sx1276mb1mas" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/FFT" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lsm6ds0" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lsm6ds3" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/DSP/Source"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Projects/End_Node/stm32l4xx_hal_msp.o: C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/Core/src/stm32l4xx_hal_msp.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_EU868 -DX_NUCLEO_IKS01A1 -DARM_MATH_CM4 '-D__FPU_PRESENT=1' -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/Core/inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/LoRaWAN/App/inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/STM32L4xx_Nucleo" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/STM32L4xx_HAL_Driver/Inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/Include" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Crypto" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Mac" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Phy" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Utilities" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/X_NUCLEO_IKS01A1" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/X_NUCLEO_IKS01A2" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/Common" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/hts221" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lps22hb" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lps25hb" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/sx1276" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Core" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/sx1276mb1mas" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/FFT" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lsm6ds0" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lsm6ds3" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/DSP/Source"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Projects/End_Node/stm32l4xx_hw.o: C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/Core/src/stm32l4xx_hw.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_EU868 -DX_NUCLEO_IKS01A1 -DARM_MATH_CM4 '-D__FPU_PRESENT=1' -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/Core/inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/LoRaWAN/App/inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/STM32L4xx_Nucleo" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/STM32L4xx_HAL_Driver/Inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/Include" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Crypto" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Mac" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Phy" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Utilities" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/X_NUCLEO_IKS01A1" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/X_NUCLEO_IKS01A2" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/Common" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/hts221" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lps22hb" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lps25hb" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/sx1276" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Core" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/sx1276mb1mas" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/FFT" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lsm6ds0" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lsm6ds3" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/DSP/Source"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Projects/End_Node/stm32l4xx_it.o: C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/Core/src/stm32l4xx_it.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_EU868 -DX_NUCLEO_IKS01A1 -DARM_MATH_CM4 '-D__FPU_PRESENT=1' -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/Core/inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/LoRaWAN/App/inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/STM32L4xx_Nucleo" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/STM32L4xx_HAL_Driver/Inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/Include" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Crypto" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Mac" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Phy" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Utilities" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/X_NUCLEO_IKS01A1" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/X_NUCLEO_IKS01A2" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/Common" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/hts221" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lps22hb" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lps25hb" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/sx1276" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Core" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/sx1276mb1mas" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/FFT" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lsm6ds0" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lsm6ds3" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/DSP/Source"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Projects/End_Node/vcom.o: C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/LoRaWAN/App/src/vcom.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_EU868 -DX_NUCLEO_IKS01A1 -DARM_MATH_CM4 '-D__FPU_PRESENT=1' -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/Core/inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/LoRaWAN/App/inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/STM32L4xx_Nucleo" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/STM32L4xx_HAL_Driver/Inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/Include" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Crypto" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Mac" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Phy" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Utilities" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/X_NUCLEO_IKS01A1" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/X_NUCLEO_IKS01A2" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/Common" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/hts221" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lps22hb" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lps25hb" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/sx1276" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Core" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/sx1276mb1mas" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/FFT" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lsm6ds0" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lsm6ds3" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/DSP/Source"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


