################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Mac/region/Region.c \
C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Mac/region/RegionAS923.c \
C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Mac/region/RegionAU915.c \
C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Mac/region/RegionCN470.c \
C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Mac/region/RegionCN779.c \
C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Mac/region/RegionCommon.c \
C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Mac/region/RegionEU433.c \
C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Mac/region/RegionEU868.c \
C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Mac/region/RegionIN865.c \
C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Mac/region/RegionKR920.c \
C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Mac/region/RegionRU864.c \
C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Mac/region/RegionUS915.c 

OBJS += \
./Middlewares/LoRaWAN/Mac/Region/Region.o \
./Middlewares/LoRaWAN/Mac/Region/RegionAS923.o \
./Middlewares/LoRaWAN/Mac/Region/RegionAU915.o \
./Middlewares/LoRaWAN/Mac/Region/RegionCN470.o \
./Middlewares/LoRaWAN/Mac/Region/RegionCN779.o \
./Middlewares/LoRaWAN/Mac/Region/RegionCommon.o \
./Middlewares/LoRaWAN/Mac/Region/RegionEU433.o \
./Middlewares/LoRaWAN/Mac/Region/RegionEU868.o \
./Middlewares/LoRaWAN/Mac/Region/RegionIN865.o \
./Middlewares/LoRaWAN/Mac/Region/RegionKR920.o \
./Middlewares/LoRaWAN/Mac/Region/RegionRU864.o \
./Middlewares/LoRaWAN/Mac/Region/RegionUS915.o 

C_DEPS += \
./Middlewares/LoRaWAN/Mac/Region/Region.d \
./Middlewares/LoRaWAN/Mac/Region/RegionAS923.d \
./Middlewares/LoRaWAN/Mac/Region/RegionAU915.d \
./Middlewares/LoRaWAN/Mac/Region/RegionCN470.d \
./Middlewares/LoRaWAN/Mac/Region/RegionCN779.d \
./Middlewares/LoRaWAN/Mac/Region/RegionCommon.d \
./Middlewares/LoRaWAN/Mac/Region/RegionEU433.d \
./Middlewares/LoRaWAN/Mac/Region/RegionEU868.d \
./Middlewares/LoRaWAN/Mac/Region/RegionIN865.d \
./Middlewares/LoRaWAN/Mac/Region/RegionKR920.d \
./Middlewares/LoRaWAN/Mac/Region/RegionRU864.d \
./Middlewares/LoRaWAN/Mac/Region/RegionUS915.d 


# Each subdirectory must supply rules for building sources it contributes
Middlewares/LoRaWAN/Mac/Region/Region.o: C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Mac/region/Region.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_EU868 -DX_NUCLEO_IKS01A1 -DARM_MATH_CM4 '-D__FPU_PRESENT=1' -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/Core/inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/LoRaWAN/App/inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/STM32L4xx_Nucleo" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/STM32L4xx_HAL_Driver/Inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/Include" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Crypto" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Mac" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Phy" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Utilities" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/X_NUCLEO_IKS01A1" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/X_NUCLEO_IKS01A2" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/Common" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/hts221" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lps22hb" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lps25hb" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/sx1276" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Core" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/sx1276mb1mas" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/FFT" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lsm6ds0" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lsm6ds3" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/DSP/Source"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Middlewares/LoRaWAN/Mac/Region/RegionAS923.o: C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Mac/region/RegionAS923.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_EU868 -DX_NUCLEO_IKS01A1 -DARM_MATH_CM4 '-D__FPU_PRESENT=1' -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/Core/inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/LoRaWAN/App/inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/STM32L4xx_Nucleo" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/STM32L4xx_HAL_Driver/Inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/Include" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Crypto" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Mac" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Phy" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Utilities" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/X_NUCLEO_IKS01A1" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/X_NUCLEO_IKS01A2" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/Common" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/hts221" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lps22hb" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lps25hb" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/sx1276" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Core" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/sx1276mb1mas" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/FFT" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lsm6ds0" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lsm6ds3" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/DSP/Source"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Middlewares/LoRaWAN/Mac/Region/RegionAU915.o: C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Mac/region/RegionAU915.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_EU868 -DX_NUCLEO_IKS01A1 -DARM_MATH_CM4 '-D__FPU_PRESENT=1' -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/Core/inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/LoRaWAN/App/inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/STM32L4xx_Nucleo" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/STM32L4xx_HAL_Driver/Inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/Include" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Crypto" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Mac" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Phy" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Utilities" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/X_NUCLEO_IKS01A1" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/X_NUCLEO_IKS01A2" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/Common" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/hts221" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lps22hb" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lps25hb" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/sx1276" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Core" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/sx1276mb1mas" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/FFT" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lsm6ds0" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lsm6ds3" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/DSP/Source"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Middlewares/LoRaWAN/Mac/Region/RegionCN470.o: C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Mac/region/RegionCN470.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_EU868 -DX_NUCLEO_IKS01A1 -DARM_MATH_CM4 '-D__FPU_PRESENT=1' -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/Core/inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/LoRaWAN/App/inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/STM32L4xx_Nucleo" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/STM32L4xx_HAL_Driver/Inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/Include" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Crypto" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Mac" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Phy" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Utilities" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/X_NUCLEO_IKS01A1" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/X_NUCLEO_IKS01A2" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/Common" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/hts221" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lps22hb" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lps25hb" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/sx1276" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Core" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/sx1276mb1mas" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/FFT" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lsm6ds0" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lsm6ds3" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/DSP/Source"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Middlewares/LoRaWAN/Mac/Region/RegionCN779.o: C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Mac/region/RegionCN779.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_EU868 -DX_NUCLEO_IKS01A1 -DARM_MATH_CM4 '-D__FPU_PRESENT=1' -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/Core/inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/LoRaWAN/App/inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/STM32L4xx_Nucleo" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/STM32L4xx_HAL_Driver/Inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/Include" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Crypto" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Mac" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Phy" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Utilities" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/X_NUCLEO_IKS01A1" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/X_NUCLEO_IKS01A2" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/Common" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/hts221" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lps22hb" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lps25hb" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/sx1276" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Core" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/sx1276mb1mas" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/FFT" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lsm6ds0" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lsm6ds3" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/DSP/Source"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Middlewares/LoRaWAN/Mac/Region/RegionCommon.o: C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Mac/region/RegionCommon.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_EU868 -DX_NUCLEO_IKS01A1 -DARM_MATH_CM4 '-D__FPU_PRESENT=1' -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/Core/inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/LoRaWAN/App/inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/STM32L4xx_Nucleo" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/STM32L4xx_HAL_Driver/Inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/Include" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Crypto" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Mac" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Phy" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Utilities" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/X_NUCLEO_IKS01A1" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/X_NUCLEO_IKS01A2" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/Common" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/hts221" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lps22hb" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lps25hb" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/sx1276" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Core" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/sx1276mb1mas" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/FFT" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lsm6ds0" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lsm6ds3" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/DSP/Source"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Middlewares/LoRaWAN/Mac/Region/RegionEU433.o: C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Mac/region/RegionEU433.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_EU868 -DX_NUCLEO_IKS01A1 -DARM_MATH_CM4 '-D__FPU_PRESENT=1' -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/Core/inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/LoRaWAN/App/inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/STM32L4xx_Nucleo" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/STM32L4xx_HAL_Driver/Inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/Include" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Crypto" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Mac" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Phy" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Utilities" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/X_NUCLEO_IKS01A1" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/X_NUCLEO_IKS01A2" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/Common" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/hts221" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lps22hb" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lps25hb" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/sx1276" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Core" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/sx1276mb1mas" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/FFT" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lsm6ds0" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lsm6ds3" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/DSP/Source"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Middlewares/LoRaWAN/Mac/Region/RegionEU868.o: C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Mac/region/RegionEU868.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_EU868 -DX_NUCLEO_IKS01A1 -DARM_MATH_CM4 '-D__FPU_PRESENT=1' -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/Core/inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/LoRaWAN/App/inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/STM32L4xx_Nucleo" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/STM32L4xx_HAL_Driver/Inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/Include" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Crypto" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Mac" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Phy" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Utilities" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/X_NUCLEO_IKS01A1" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/X_NUCLEO_IKS01A2" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/Common" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/hts221" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lps22hb" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lps25hb" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/sx1276" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Core" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/sx1276mb1mas" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/FFT" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lsm6ds0" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lsm6ds3" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/DSP/Source"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Middlewares/LoRaWAN/Mac/Region/RegionIN865.o: C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Mac/region/RegionIN865.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_EU868 -DX_NUCLEO_IKS01A1 -DARM_MATH_CM4 '-D__FPU_PRESENT=1' -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/Core/inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/LoRaWAN/App/inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/STM32L4xx_Nucleo" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/STM32L4xx_HAL_Driver/Inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/Include" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Crypto" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Mac" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Phy" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Utilities" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/X_NUCLEO_IKS01A1" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/X_NUCLEO_IKS01A2" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/Common" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/hts221" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lps22hb" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lps25hb" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/sx1276" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Core" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/sx1276mb1mas" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/FFT" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lsm6ds0" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lsm6ds3" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/DSP/Source"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Middlewares/LoRaWAN/Mac/Region/RegionKR920.o: C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Mac/region/RegionKR920.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_EU868 -DX_NUCLEO_IKS01A1 -DARM_MATH_CM4 '-D__FPU_PRESENT=1' -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/Core/inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/LoRaWAN/App/inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/STM32L4xx_Nucleo" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/STM32L4xx_HAL_Driver/Inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/Include" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Crypto" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Mac" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Phy" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Utilities" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/X_NUCLEO_IKS01A1" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/X_NUCLEO_IKS01A2" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/Common" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/hts221" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lps22hb" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lps25hb" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/sx1276" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Core" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/sx1276mb1mas" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/FFT" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lsm6ds0" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lsm6ds3" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/DSP/Source"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Middlewares/LoRaWAN/Mac/Region/RegionRU864.o: C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Mac/region/RegionRU864.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_EU868 -DX_NUCLEO_IKS01A1 -DARM_MATH_CM4 '-D__FPU_PRESENT=1' -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/Core/inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/LoRaWAN/App/inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/STM32L4xx_Nucleo" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/STM32L4xx_HAL_Driver/Inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/Include" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Crypto" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Mac" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Phy" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Utilities" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/X_NUCLEO_IKS01A1" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/X_NUCLEO_IKS01A2" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/Common" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/hts221" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lps22hb" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lps25hb" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/sx1276" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Core" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/sx1276mb1mas" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/FFT" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lsm6ds0" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lsm6ds3" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/DSP/Source"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Middlewares/LoRaWAN/Mac/Region/RegionUS915.o: C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Mac/region/RegionUS915.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_EU868 -DX_NUCLEO_IKS01A1 -DARM_MATH_CM4 '-D__FPU_PRESENT=1' -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/Core/inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Projects/STM32L476RG-Nucleo/Applications/LoRa/End_Node/LoRaWAN/App/inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/STM32L4xx_Nucleo" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/STM32L4xx_HAL_Driver/Inc" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/Include" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Crypto" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Mac" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Phy" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Utilities" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/X_NUCLEO_IKS01A1" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/X_NUCLEO_IKS01A2" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/Common" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/hts221" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lps22hb" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lps25hb" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/sx1276" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Middlewares/Third_Party/LoRaWAN/Core" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/sx1276mb1mas" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/FFT" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lsm6ds0" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/BSP/Components/lsm6ds3" -I"C:/Users/Giammario/Desktop/STM32CubeExpansion_LRWAN_V1.2.2/Drivers/CMSIS/DSP/Source"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


